spring.application.name=AuthUnidate
server.port=3982

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ThueTro;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT config
jwt.secret=CHANGE_ME_TO_STRONG_SECRET_KEY_MIN_64_BYTES_1234567890ABCDEFG
jwt.expiration=15
refreshjwt.expiration=2

# Mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Firebase Admin SDK
firebase.enabled=true
# firebase.credentials.path=classpath:firebase-service-account.json
# firebase.credentials.path=D:/secrets/firebase-service-account.json

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
